<?php session_start();$_SESSION['redirect_url']=$_SERVER['REQUEST_URI'];if(!isset($_SESSION['loggedin'])||$_SESSION['loggedin']!==true){header("Location: ../login.php");exit;}include '../Header.php'; ?><div class="ttm-page-title-row"><div class="ttm-bg-layer ttm-page-title-row-bg-layer"></div><div class="container"><div class="row"><div class="text-center col-md-12"><div class="ttm-textcolor-white title-box"><div class="ttm-textcolor-white page-title-heading"><h1 class="title">Contact Details</h1></div><div class="breadcrumb-wrapper"><span><a href="/"title="Homepage"><i class="ti ti-home"></i> Home </a></span><span class="ttm-bread-sep">: : </span><span><span class="ttm-textcolor-skincolor">Contact Details</span></span></div></div></div></div></div></div><section class="error-404"><header class="text-center section-title"><h5>Contact Details</h5></header><div class="container px-2"><div class="row"><div class="col-md-12"><div class="text-center row-title style4"><section><div class="table-responsive"><table class="table table-bordered table-hover table-striped"><thead><tr><th>Name</th><th>Occupation</th><th>Mobile</th><th>Email</th><th>City</th><th>Diet Requirement</th><th>Created At</th><th>Edit</th><th>Delete</th></tr></thead><tbody><?php require_once __DIR__ . '/../json_db.php';$rows=jd_read('user_details');usort($rows,function($a,$b){return strcmp((string)($b['created_at']??''),(string)($a['created_at']??''));});if(!empty($rows)){foreach($rows as $row){echo "<tr>";foreach(array('name','occupation','mobile','email','city','diet','created_at') as $col){echo "<td>".htmlspecialchars((string)($row[$col]??''),ENT_QUOTES,'UTF-8')."</td>";}echo '<td><a href="edit_contact_user.php?id='.$row['id'].'"><i class="fa fa-edit"></i></a></td>';echo "<td><a class='delete-button' data-id='".$row['id']."'><i class='fa fa-trash'></i></a>\n</td>";echo "</tr>";}}else{echo "<tr><td colspan='8'>No records found.</td></tr>";} ?></tbody></table></div></section></div></div></div></div></section><div class="fade modal"role="dialog"aria-hidden="true"aria-labelledby="deleteModalLabel"id="deleteModal"tabindex="-1"><div class="modal-dialog modal-dialog-centered"role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"id="deleteModalLabel">Confirm Deletion</h5><button class="close"type="button"data-dismiss="modal"aria-label="Close"><span aria-hidden="true">×</span></button></div><div class="modal-body">Are you sure you want to delete this record?</div><div class="modal-footer"><button class="btn btn-secondary"type="button"data-dismiss="modal">Cancel</button> <button class="btn btn-danger"type="button"id="confirmDeleteButton">Delete</button></div></div></div></div><script>// Add event listener to delete buttons
  const deleteButtons = document.querySelectorAll('.delete-button');
  deleteButtons.forEach(button => {
    button.addEventListener('click', (event) => {
      event.preventDefault(); // Prevent the default anchor behavior
      const id = event.target.closest('tr').querySelector('.delete-button').dataset.id;
      // Show the modal when the delete button is clicked
      $('#deleteModal').modal('show');

      // Add event listener to the "Delete" button inside the modal
      document.getElementById('confirmDeleteButton').addEventListener('click', () => {
        // Handle the delete logic here, for example, using AJAX to delete the record from the database.
        // In this example, we will redirect to a delete.php page passing the id as a query parameter.
        window.location.href = `./delete_contact.php?id=${id}`;
      });
    });
  });</script><?php include '../footer.php'; ?>