<?php
/* Auto-generated by admin/auto_beautify.php - do not edit. */
$html = (string) file_get_contents($argv[1]);
$html = preg_replace("/^\xEF\xBB\xBF/", "", $html);
set_time_limit(60);

function blog_beautify_content($html)
{
    if (!is_string($html) || trim($html) === '') {
        return '';
    }

    // 1) Strip the full-document wrapper saved by DOMDocument::saveHTML()
    if (preg_match('/<!DOCTYPE|<html[\s>]|<body[\s>]/i', $html)) {
        if (preg_match('/<body[^>]*>(.*)<\/body>/is', $html, $m)) {
            $html = $m[1];
        }
        $html = preg_replace('/<!DOCTYPE[^>]*>/is', '', $html);
        $html = preg_replace('/<head\b[^>]*>.*?<\/head>/is', '', $html);
        $html = preg_replace('/<\/?(?:html|body)[^>]*>/is', '', $html);
    }

    // 2) Drop HTML comments (Blogger leaves editor hints behind)
    $html = preg_replace('/<!--.*?-->/s', '', $html);

    // 2b) Markdown "**bold**" markers some editors leave behind -> real <b>
    //     tags, then drop any stray "**" so it never reaches the page.
    $html = preg_replace('/\*\*(.+?)\*\*/su', '<b>$1</b>', $html);
    $html = str_replace('**', '', $html);

    // 3) Line breaks become real paragraphs: "<br><br>" runs, and a single
    //    "<br>" that sits right before a bullet/numbered line.
    if (preg_match('/(?:<br\s*\/?>\s*){2,}/i', $html)) {
        $html = preg_replace('/(?:<br\s*\/?>\s*){2,}/i', '</p><p>', $html);
    }
    $html = preg_replace(
        '/<br\s*\/?>(?:\s|&nbsp;)*((?:&bull;|&#8226;|&#x2022;|&#8211;|&#8212;|\x{2022}|\x{00B7}|\x{25CF}|\x{25AA}|\x{25E6}|\x{2023}|\x{27A2}|\x{27A4}|\x{25B6}|\x{2756}|\*|\x{2D}|\x{2013}|\x{2014})\s*|\d{1,2}[.)]\s+)/u',
        '</p><p>$1',
        $html
    );

    $dom = new DOMDocument();
    libxml_use_internal_errors(true);
    $dom->loadHTML(
        '<meta charset="utf-8"><div id="bd-beauty-root">' . $html . '</div>',
        LIBXML_NOWARNING | LIBXML_NOERROR
    );
    libxml_clear_errors();

    $root = null;
    foreach ($dom->getElementsByTagName('div') as $div) {
        if ($div->getAttribute('id') === 'bd-beauty-root') {
            $root = $div;
            break;
        }
    }
    if (!$root) {
        return $html;
    }

    $toElement = function ($node, $tag) use ($dom) {
        $new = $dom->createElement($tag);
        while ($node->firstChild) {
            $new->appendChild($node->firstChild);
        }
        $node->parentNode->replaceChild($new, $node);
        return $new;
    };

    // 4) Remove elements that never belong in article content
    foreach (['style', 'script', 'link', 'meta', 'head', 'title', 'noscript'] as $tag) {
        while (true) {
            $nodes = $root->getElementsByTagName($tag);
            if ($nodes->length === 0) {
                break;
            }
            $node = $nodes->item(0);
            $node->parentNode->removeChild($node);
        }
    }

    // 5) Normalise attributes: small allow-list plus text-align only
    $allowed = [
        'a'      => ['href', 'title'],
        'img'    => ['src', 'alt', 'title'],
        'td'     => ['colspan', 'rowspan'],
        'th'     => ['colspan', 'rowspan'],
        'ol'     => ['start'],
        'iframe' => ['src', 'title', 'allow', 'allowfullscreen', 'frameborder'],
    ];
    foreach ($root->getElementsByTagName('*') as $el) {
        $tag = strtolower($el->nodeName);
        $attrs = [];
        while ($el->hasAttributes()) {
            $attr = $el->attributes->item(0);
            $attrs[strtolower($attr->name)] = $attr->value;
            $el->removeAttribute($attr->name);
        }

        $textAlign = '';
        if (isset($attrs['style']) && preg_match('/text-align\s*:\s*(center|right|justify)/i', $attrs['style'], $tm)) {
            $textAlign = strtolower($tm[1]);
        }
        if ($textAlign === '' && isset($attrs['align']) && in_array(strtolower($attrs['align']), ['center', 'right', 'justify'], true)) {
            $textAlign = strtolower($attrs['align']);
        }

        foreach (($allowed[$tag] ?? []) as $name) {
            if (isset($attrs[$name]) && $attrs[$name] !== '') {
                $el->setAttribute($name, $attrs[$name]);
            }
        }
        if ($textAlign !== '') {
            $el->setAttribute('style', 'text-align:' . $textAlign);
        }
    }

    // Unwrap redundant inline wrappers (their attributes were stripped above);
    // keep only wrappers that still carry a style such as text-align
    $wrappers = [];
    foreach (['span', 'font'] as $wname) {
        foreach ($root->getElementsByTagName($wname) as $w) {
            $wrappers[] = $w;
        }
    }
    foreach ($wrappers as $w) {
        if (!$w->parentNode || $w->attributes->length > 0) {
            continue;
        }
        while ($w->firstChild) {
            $w->parentNode->insertBefore($w->firstChild, $w);
        }
        $w->parentNode->removeChild($w);
    }

    // 6) Chat-export / Word HTML uses <div> paragraphs and stray <br> lines:
    //    real paragraphs, empty spacers removed, loose text kept readable.
    $blockTags = ['p','div','h1','h2','h3','h4','h5','h6','ul','ol','table','blockquote','pre','hr','figure','section','article','nav','header','footer','aside','address','form','dl'];

    $brs = [];
    foreach ($root->getElementsByTagName('br') as $br) {
        $brs[] = $br;
    }
    foreach ($brs as $br) {
        if (!$br->parentNode) {
            continue;
        }
        $prev = $br->previousSibling;
        $next = $br->nextSibling;
        $prevBlock = $prev && $prev->nodeType === XML_ELEMENT_NODE && in_array(strtolower($prev->nodeName), $blockTags, true);
        $nextBlock = $next && $next->nodeType === XML_ELEMENT_NODE && in_array(strtolower($next->nodeName), $blockTags, true);
        if ($prevBlock || $nextBlock) {
            $br->parentNode->removeChild($br);
        }
    }

    $processDiv = null;
    $processDiv = function ($container) use (&$processDiv, $dom, $blockTags) {
        $children = [];
        foreach ($container->childNodes as $n) {
            $children[] = $n;
        }
        foreach ($children as $n) {
            if ($n->nodeType === XML_ELEMENT_NODE) {
                $processDiv($n);
            }
        }

        $divs = [];
        foreach ($container->childNodes as $n) {
            if ($n->nodeType === XML_ELEMENT_NODE && strtolower($n->nodeName) === 'div') {
                $divs[] = $n;
            }
        }
        foreach ($divs as $d) {
            if (!$d->parentNode) {
                continue;
            }
            $hasBlock = false;
            $hasInline = false;
            foreach ($d->childNodes as $n) {
                if ($n->nodeType === XML_TEXT_NODE) {
                    if (trim($n->nodeValue) !== '') {
                        $hasInline = true;
                    }
                } elseif ($n->nodeType === XML_ELEMENT_NODE) {
                    $t = strtolower($n->nodeName);
                    if ($t === 'br') {
                        continue;
                    }
                    if (in_array($t, $blockTags, true)) {
                        $hasBlock = true;
                    } else {
                        $hasInline = true;
                    }
                }
            }

            if (!$hasBlock && !$hasInline) {
                // Empty or <br>-only spacer block
                $d->parentNode->removeChild($d);
                continue;
            }
            if (!$hasBlock && $hasInline) {
                // Plain paragraph container -> real <p>
                $p = $dom->createElement('p');
                while ($d->firstChild) {
                    $p->appendChild($d->firstChild);
                }
                $d->parentNode->replaceChild($p, $d);
                continue;
            }

            // Mixed content: loose inline runs become <p>, block children move up
            $parent = $d->parentNode;
            $run = [];
            $frag = [];
            $flushRun = function () use (&$run, $dom, &$frag) {
                if (count($run)) {
                    $p = $dom->createElement('p');
                    foreach ($run as $r) {
                        $p->appendChild($r);
                    }
                    $frag[] = $p;
                    $run = [];
                }
            };
            $kids = [];
            foreach ($d->childNodes as $k) {
                $kids[] = $k;
            }
            foreach ($kids as $k) {
                if ($k->nodeType === XML_TEXT_NODE) {
                    if (trim($k->nodeValue) === '') {
                        if (count($run)) {
                            $run[] = $k;
                        } else {
                            $d->removeChild($k);
                        }
                        continue;
                    }
                    $run[] = $k;
                    continue;
                }
                if ($k->nodeType !== XML_ELEMENT_NODE) {
                    continue;
                }
                $t = strtolower($k->nodeName);
                if ($t === 'br') {
                    $d->removeChild($k);
                    continue;
                }
                if (in_array($t, $blockTags, true)) {
                    $flushRun();
                    $frag[] = $k;
                } else {
                    $run[] = $k;
                }
            }
            $flushRun();
            foreach ($frag as $f) {
                $parent->insertBefore($f, $d);
            }
            $parent->removeChild($d);
        }
    };
    $processDiv($root);

    // 7) Plain "• line" / "1. line" paragraphs become real bullet/numbered lists
    $ulItem = '/^\s*(?:•|·|●|▪|◦|‣|➢|➤|►|❖|\*|[-–—])(?:\s+|$)/u';
    $olItem = '/^\s*(\d{1,2})[.)](?:\s+|$)/u';

    $classifyItem = function ($text) use ($ulItem, $olItem) {
        $text = trim(preg_replace('/\s+/u', ' ', (string)$text));
        if ($text === '') {
            return null;
        }
        if (preg_match($ulItem, $text)) {
            return ['ul', 0];
        }
        if (preg_match($olItem, $text, $m)) {
            return ['ol', (int)$m[1]];
        }
        return null;
    };

    // Marker + short bold label ("* **DO's:**") is a sub-heading, not a list item
    $labelCandidates = [];
    foreach ($root->getElementsByTagName('p') as $p) {
        $labelCandidates[] = $p;
    }
    foreach ($labelCandidates as $p) {
        if (!$p->parentNode) {
            continue;
        }
        $cls = $classifyItem((string)$p->textContent);
        if ($cls === null) {
            continue;
        }
        $marker = ($cls[0] === 'ol') ? $olItem : $ulItem;
        $norm = trim(preg_replace('/\s+/u', ' ', (string)$p->textContent));
        $remainder = trim(preg_replace($marker, '', $norm, 1));
        if ($remainder === '' || mb_strlen($remainder) > 40 || substr($remainder, -1) !== ':') {
            continue;
        }
        $bold = '';
        foreach ($p->getElementsByTagName('b') as $bn) {
            $bold .= $bn->textContent . ' ';
        }
        foreach ($p->getElementsByTagName('strong') as $bn) {
            $bold .= $bn->textContent . ' ';
        }
        if (trim(preg_replace('/\s+/u', ' ', $bold)) !== $remainder) {
            continue;
        }
        // Everything outside the bold element may only be marker/whitespace
        $stray = false;
        $strip = function ($n) use (&$strip, &$stray, $marker) {
            foreach ($n->childNodes as $cn) {
                if ($cn->nodeType === XML_TEXT_NODE) {
                    if (!in_array(strtolower($cn->parentNode->nodeName), ['b', 'strong'], true)) {
                        $left = preg_replace($marker, '', $cn->nodeValue, 1);
                        if (preg_replace('/\s+/u', '', str_replace("\xC2\xA0", '', $left)) !== '') {
                            $stray = true;
                        }
                    }
                } elseif ($cn->nodeType === XML_ELEMENT_NODE) {
                    if (!in_array(strtolower($cn->nodeName), ['b', 'strong'], true)) {
                        $stray = true;
                    } else {
                        $strip($cn);
                    }
                }
            }
        };
        $strip($p);
        if ($stray) {
            continue;
        }
        // Drop marker/whitespace text nodes, promote paragraph to <h4>
        $drop = [];
        foreach ($p->childNodes as $cn) {
            if ($cn->nodeType === XML_TEXT_NODE) {
                $cn->nodeValue = '';
                $drop[] = $cn;
            }
        }
        foreach ($drop as $dn) {
            if ($dn->parentNode) {
                $dn->parentNode->removeChild($dn);
            }
        }
        $h = $dom->createElement('h4');
        while ($p->firstChild) {
            $h->appendChild($p->firstChild);
        }
        $p->parentNode->replaceChild($h, $p);
    }

    // Paragraphs holding several line-broken items ("1. a\n2. b") split apart
    $splitCandidates = [];
    foreach ($root->getElementsByTagName('p') as $p) {
        $splitCandidates[] = $p;
    }
    foreach ($splitCandidates as $p) {
        if (!$p->parentNode || $p->getElementsByTagName('*')->length > 0) {
            continue;
        }
        $raw = (string)$p->textContent;
        if (strpos($raw, "\n") === false) {
            continue;
        }
        $lines = preg_split('/\r?\n/', $raw);
        if (count($lines) < 2) {
            continue;
        }
        $ok = true;
        $items = [];
        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '') {
                continue;
            }
            if ($classifyItem($line) === null) {
                $ok = false;
                break;
            }
            $items[] = $line;
        }
        if (!$ok || count($items) < 2) {
            continue;
        }
        $parent = $p->parentNode;
        foreach ($items as $line) {
            $np = $dom->createElement('p');
            $np->appendChild($dom->createTextNode($line));
            $parent->insertBefore($np, $p);
        }
        $parent->removeChild($p);
    }

    // A numbered item wrapped inside the previous item after a <br>
    // ("... sit down to work.<br><b>5. </b><b>Eat a balanced diet -</b> ...")
    // is a real list item, not a continuation of the previous one. Split it
    // into its own paragraph so the list converter marks it "5.".
    $brSplitCandidates = [];
    foreach ($root->getElementsByTagName('p') as $p) {
        $brSplitCandidates[] = $p;
    }
    foreach ($brSplitCandidates as $p) {
        if (!$p->parentNode) {
            continue;
        }
        if ($classifyItem($p->textContent) === null) {
            continue;
        }
        $cut = true;
        while ($cut) {
            $cut = false;
            $kids = [];
            foreach ($p->childNodes as $cn) {
                $kids[] = $cn;
            }
            $br = null;
            foreach ($kids as $cn) {
                if ($cn->nodeType !== XML_ELEMENT_NODE || strtolower($cn->nodeName) !== 'br') {
                    continue;
                }
                if ($cn->parentNode !== $p) {
                    continue;
                }
                $nxt = $cn->nextSibling;
                while ($nxt && $nxt->nodeType === XML_TEXT_NODE && trim($nxt->nodeValue) === '') {
                    $nxt = $nxt->nextSibling;
                }
                if ($nxt === null) {
                    continue;
                }
                $prefix = '';
                $guard = $nxt;
                while ($guard !== null && $guard !== $p && mb_strlen($prefix) < 14) {
                    if ($guard->nodeType === XML_TEXT_NODE) {
                        $prefix .= $guard->nodeValue;
                    } elseif ($guard->nodeType === XML_ELEMENT_NODE) {
                        $gt = strtolower($guard->nodeName);
                        if (in_array($gt, $blockTags, true) || $gt === 'br') {
                            break;
                        }
                        $prefix .= $guard->textContent;
                    }
                    $guard = $guard->nextSibling;
                }
                if (preg_match('/^\s*(\d{1,2})[.)](?:\s+|$)/u', $prefix)) {
                    $br = $cn;
                    break;
                }
            }
            if ($br === null) {
                break;
            }
            $np = $dom->createElement('p');
            $p->parentNode->insertBefore($np, $p->nextSibling);
            $move = $br;
            while ($move !== null) {
                $m2 = $move->nextSibling;
                $np->appendChild($move);
                $move = $m2;
            }
            if ($np->firstChild && strtolower($np->firstChild->nodeName) === 'br') {
                $np->removeChild($np->firstChild);
            }
            $p = $np;
            $cut = true;
        }
    }

    $convertListsIn = null;
    $convertListsIn = function ($container) use (&$convertListsIn, $dom, $classifyItem, $ulItem, $olItem) {
        $child = $container->firstChild;
        while ($child !== null) {
            if ($child->nodeType === XML_ELEMENT_NODE) {
                $tag = strtolower($child->nodeName);
                if ($tag === 'p' && $classifyItem($child->textContent) !== null) {
                    $first = $classifyItem($child->textContent);
                    $olSubRegex = '/^\s*(i{1,3}|iv|v|vi{1,3}|ix|x[iv]{0,4})[.)]/iu';
                    $run = [];
                    $subMap = [];
                    $subs = [];
                    $cursor = $child;
                    $expect = $first[1];
                    while ($cursor !== null) {
                        // Blogger/Word source may carry real newlines between
                        // block tags, which DOMDocument keeps as whitespace text
                        // nodes. Skip them so a run of <p> items is not broken.
                        if ($cursor->nodeType === XML_TEXT_NODE || $cursor->nodeType === XML_CDATA_SECTION_NODE) {
                            if (trim($cursor->nodeValue) === '') {
                                $cursor = $cursor->nextSibling;
                                continue;
                            }
                            break;
                        }
                        if ($cursor->nodeType !== XML_ELEMENT_NODE || strtolower($cursor->nodeName) !== 'p') {
                            break;
                        }
                        if (trim($cursor->textContent, " \t\n\r\0\x0B\xC2\xA0") === '') {
                            $cursor = $cursor->nextSibling;
                            continue;
                        }
                        $c = $classifyItem($cursor->textContent);
                        if ($c === null) {
                            // i) / ii) subtitles belong to the previous numbered item
                            if ($first[0] === 'ol' && count($run) && preg_match($olSubRegex, $cursor->textContent)) {
                                $subs[] = $cursor;
                                $cursor = $cursor->nextSibling;
                                continue;
                            }
                            break;
                        }
                        if ($first[0] === 'ol' && $c[0] === 'ul') {
                            // Bullet lines under a numbered item ("- Calcium content: ...")
                            $subs[] = $cursor;
                            $cursor = $cursor->nextSibling;
                            continue;
                        }
                        if ($c[0] !== $first[0]) {
                            break;
                        }
                        if ($first[0] === 'ol' && $c[1] !== $expect) {
                            break;
                        }
                        $subMap[count($run)] = $subs;
                        $subs = [];
                        $run[] = $cursor;
                        if ($first[0] === 'ol') {
                            $expect++;
                        }
                        $cursor = $cursor->nextSibling;
                    }
                    $subMap[count($run)] = $subs;
                    if ($cursor === $child) {
                        $child = $child->nextSibling;
                        continue;
                    }
                    if (count($run) >= 2) {
                        $list = $dom->createElement($first[0]);
                        if ($first[0] === 'ol' && $first[1] > 1) {
                            $list->setAttribute('style', 'counter-reset: bd ' . ($first[1] - 1));
                        }
                        $parent = $run[0]->parentNode;
                        $parent->insertBefore($list, $run[0]);
                        $marker = ($first[0] === 'ol') ? $olItem : $ulItem;
                        foreach ($run as $i => $p) {
                            $li = $dom->createElement('li');
                            while ($p->firstChild) {
                                $li->appendChild($p->firstChild);
                            }
                            $list->appendChild($li);
                            // Bullets gathered between item N and item N+1 belong
                            // to item N (subMap is keyed by the item that FOLLOWS).
                            $attachIdx = $i + 1;
                            if (isset($subMap[$attachIdx]) && count($subMap[$attachIdx])) {
                                $inner = $dom->createElement('ul');
                                foreach ($subMap[$attachIdx] as $sp) {
                                    $sli = $dom->createElement('li');
                                    while ($sp->firstChild) {
                                        $sli->appendChild($sp->firstChild);
                                    }
                                    $inner->appendChild($sli);
                                    if ($sp->parentNode) {
                                        $sp->parentNode->removeChild($sp);
                                    }
                                }
                                $li->appendChild($inner);
                            }
                            if ($p->parentNode) {
                                $p->parentNode->removeChild($p);
                            }
                        }
                        $stripMarker = function ($li, $re) {
                            $texts = [];
                            $collect = function ($n) use (&$collect, &$texts) {
                                foreach ($n->childNodes as $c) {
                                    if ($c->nodeType === XML_TEXT_NODE) {
                                        $texts[] = $c;
                                    } elseif ($c->nodeType === XML_ELEMENT_NODE) {
                                        $collect($c);
                                    }
                                }
                            };
                            $collect($li);
                            $joined = '';
                            foreach ($texts as $t) {
                                $joined .= $t->nodeValue;
                            }
                            if (preg_match($re, $joined, $mm)) {
                                $cut = strlen($mm[0]);
                                foreach ($texts as $t) {
                                    if ($cut <= 0) {
                                        break;
                                    }
                                    $len = strlen($t->nodeValue);
                                    if ($len <= $cut) {
                                        $cut -= $len;
                                        $t->nodeValue = '';
                                    } else {
                                        $t->nodeValue = substr($t->nodeValue, $cut);
                                        $cut = 0;
                                    }
                                }
                            }
                            if (count($texts)) {
                                foreach ($texts as $t) {
                                    if (trim($t->nodeValue) !== '') {
                                        $t->nodeValue = ltrim($t->nodeValue, " \t\n\r\0\x0B\xC2\xA0");
                                        break;
                                    }
                                }
                            }
                        };
                        foreach ($list->childNodes as $li) {
                            $stripMarker($li, $marker);
                            foreach ($li->getElementsByTagName('li') as $sli) {
                                if ($sli->parentNode && strtolower($sli->parentNode->nodeName) === 'ul') {
                                    $stripMarker($sli, $ulItem);
                                    $stripMarker($sli, $olSubRegex);
                                }
                            }
                        }
                    }
                    $child = $cursor;
                    continue;
                }
                if (in_array($tag, ['div', 'section', 'article'], true)) {
                    $convertListsIn($child);
                }
            }
            $child = $child->nextSibling;
        }
    };
    $convertListsIn($root);

    // A lone numbered paragraph that resumes an earlier list ("6. Breathing
    // exercises" after an unrelated paragraph) should still render as item
    // "6.", not as literal text. Only when a <ol> exists earlier among the
    // sibling blocks and the number continues past 1 (a real continuation).
    $singleItems = [];
    foreach ($root->getElementsByTagName('p') as $p) {
        $singleItems[] = $p;
    }
    foreach ($singleItems as $p) {
        if (!$p->parentNode) {
            continue;
        }
        $cl = $classifyItem($p->textContent);
        if ($cl === null || $cl[0] !== 'ol' || $cl[1] <= 1) {
            continue;
        }
        $anc = $p->parentNode;
        $inTd = false;
        while ($anc) {
            if (in_array(strtolower($anc->nodeName), ['td', 'th'], true)) {
                $inTd = true;
                break;
            }
            $anc = $anc->parentNode;
        }
        if ($inTd) {
            continue;
        }
        $hasList = false;
        $node = $p->previousSibling;
        while ($node !== null) {
            if ($node->nodeType === XML_ELEMENT_NODE) {
                $t = strtolower($node->nodeName);
                if ($t === 'ol') {
                    $hasList = true;
                    break;
                }
                if (in_array($t, ['table', 'blockquote'], true)) {
                    break;
                }
            }
            $node = $node->previousSibling;
        }
        if (!$hasList) {
            continue;
        }
        $list = $dom->createElement('ol');
        $list->setAttribute('style', 'counter-reset: bd ' . ($cl[1] - 1));
        $li = $dom->createElement('li');
        while ($p->firstChild) {
            $li->appendChild($p->firstChild);
        }
        $list->appendChild($li);
        $p->parentNode->replaceChild($list, $p);
        $texts = [];
        $collect = function ($n) use (&$collect, &$texts) {
            foreach ($n->childNodes as $c) {
                if ($c->nodeType === XML_TEXT_NODE) {
                    $texts[] = $c;
                } elseif ($c->nodeType === XML_ELEMENT_NODE) {
                    $collect($c);
                }
            }
        };
        $collect($li);
        $joined = '';
        foreach ($texts as $t) {
            $joined .= $t->nodeValue;
        }
        if (preg_match($olItem, $joined, $mm)) {
            $cut = strlen($mm[0]);
            foreach ($texts as $t) {
                if ($cut <= 0) {
                    break;
                }
                $len = strlen($t->nodeValue);
                if ($len <= $cut) {
                    $cut -= $len;
                    $t->nodeValue = '';
                } else {
                    $t->nodeValue = substr($t->nodeValue, $cut);
                    $cut = 0;
                }
            }
        }
        if (count($texts)) {
            foreach ($texts as $t) {
                if (trim($t->nodeValue) !== '') {
                    $t->nodeValue = ltrim($t->nodeValue, " \t\n\r\0\x0B\xC2\xA0");
                    break;
                }
            }
        }
    }

    // 8) Images: lazy-load, alt text, lightbox-friendly cursor
    foreach ($root->getElementsByTagName('img') as $img) {
        $img->setAttribute('loading', 'lazy');
        if ($img->getAttribute('alt') === '') {
            $img->setAttribute('alt', 'Bite And Diet');
        }
        $img->setAttribute('class', 'post-img');
    }

    // 9) Unwrap links that only wrap images (the lightbox opens them instead)
    $anchors = [];
    foreach ($root->getElementsByTagName('a') as $a) {
        $anchors[] = $a;
    }
    foreach ($anchors as $a) {
        if (!$a->parentNode) {
            continue;
        }
        $imgs = [];
        foreach ($a->getElementsByTagName('img') as $im) {
            $imgs[] = $im;
        }
        if (trim($a->textContent) === '' && count($imgs) > 0) {
            foreach ($imgs as $im) {
                $a->parentNode->insertBefore($im, $a);
            }
            $a->parentNode->removeChild($a);
        } elseif (trim($a->textContent) === '' && $a->getAttribute('href') === '') {
            $a->parentNode->removeChild($a);
        }
    }

    // 10) Demote oversized headings so every post uses the same heading scale
    //     (the page already has its own <h1>; content tops out at <h3>)
    foreach ([['h1', 'h3'], ['h2', 'h3'], ['h5', 'h4'], ['h6', 'h4']] as $pair) {
        $nodes = [];
        foreach ($root->getElementsByTagName($pair[0]) as $n) {
            $nodes[] = $n;
        }
        foreach ($nodes as $n) {
            if ($n->parentNode) {
                $toElement($n, $pair[1]);
            }
        }
    }

    // 11) Bold pseudo-headings become real headings
    $inlineParents = ['p', 'li', 'td', 'th', 'dd', 'dt', 'blockquote', 'a', 'span', 'em', 'i', 'font', 'label', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'];
    $blockTags = ['p', 'div', 'ul', 'ol', 'table', 'blockquote', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'section', 'article', 'figure', 'tr', 'pre', 'br'];
    $boldNodes = [];
    foreach ($root->getElementsByTagName('b') as $n) {
        $boldNodes[] = $n;
    }
    foreach ($root->getElementsByTagName('strong') as $n) {
        $boldNodes[] = $n;
    }
    foreach ($boldNodes as $b) {
        if (!$b->parentNode || !($b->parentNode instanceof DOMElement)) {
            continue;
        }
        $text = trim(preg_replace('/\s+/u', ' ', $b->textContent));
        if ($text === '' || mb_strlen($text) > 250) {
            continue;
        }
        $parent = $b->parentNode;
        $parentTag = strtolower($parent->nodeName);

        // Never promote bold text inside tables to headings - table cells
        // stay compact (first row is styled as the header by CSS)
        $inTable = false;
        $walkUp = $parent;
        while ($walkUp !== null && $walkUp instanceof DOMElement) {
            $upTag = strtolower($walkUp->nodeName);
            if (in_array($upTag, ['table', 'thead', 'tbody', 'tr', 'td', 'th'], true)) {
                $inTable = true;
                break;
            }
            $walkUp = $walkUp->parentNode;
        }
        if ($inTable) {
            continue;
        }

        // <p> whose text is entirely bold becomes a subheading <h3>
        // (handles inline wrappers and multiple <b> runs in one paragraph)
        if ($parentTag === 'p') {
            $ok = true;
            $hasBold = false;
            $walkBold = function ($node, $inBold) use (&$walkBold, &$ok, &$hasBold) {
                $junk = [];
                foreach ($node->childNodes as $cn) {
                    if ($cn->nodeType === XML_TEXT_NODE) {
                        if (preg_match('/\S/u', $cn->nodeValue) && !$inBold) {
                            // Punctuation glue between bold runs (e.g. "<b>1</b>.<b>Title</b>")
                            // belongs to the heading, not to body text.
                            $plain = trim(preg_replace('/\s+/u', ' ', $cn->nodeValue));
                            if (preg_match('/^[\p{P}\p{S}]+$/u', $plain)) {
                                $cn->nodeValue = $plain . ' ';
                            } else {
                                $ok = false;
                            }
                        }
                        continue;
                    }
                    if ($cn->nodeType !== XML_ELEMENT_NODE) {
                        $ok = false;
                        continue;
                    }
                    $t = strtolower($cn->nodeName);
                    if ($t === 'b' || $t === 'strong') {
                        $hasBold = true;
                        $walkBold($cn, true);
                    } elseif (in_array($t, ['span', 'font', 'i', 'em', 'u'], true)) {
                        $walkBold($cn, $inBold);
                    } elseif (in_array($t, ['img', 'iframe', 'video', 'audio', 'table', 'ul', 'ol', 'blockquote'], true)) {
                        // Real content inside a would-be heading: reject instead of
                        // deleting it (the empty-shell branch below removes nodes
                        // without text, which would otherwise eat media/tables).
                        $ok = false;
                    } elseif (!preg_match('/\S/u', $cn->textContent)) {
                        // Blogger leaves empty shells (e.g. "<p/>" from br cleanup)
                        // inside bold text - drop them so the heading still converts.
                        $junk[] = $cn;
                    } else {
                        $ok = false;
                    }
                }
                foreach ($junk as $jn) {
                    if ($jn->parentNode) {
                        $jn->parentNode->removeChild($jn);
                    }
                }
            };
            $walkBold($parent, false);
            if ($ok && $hasBold && $parent->parentNode) {
                $h = $dom->createElement('h3');
                while ($parent->firstChild) {
                    $h->appendChild($parent->firstChild);
                }
                $parent->parentNode->replaceChild($h, $parent);
            }
            continue;
        }
        if (in_array($parentTag, $inlineParents, true)) {
            continue;
        }

        // Standalone bold line: neighbours are blocks (or nothing)
        $prev = $b->previousSibling;
        while ($prev && $prev->nodeType === XML_TEXT_NODE && trim($prev->nodeValue) === '') {
            $prev = $prev->previousSibling;
        }
        $next = $b->nextSibling;
        while ($next && $next->nodeType === XML_TEXT_NODE && trim($next->nodeValue) === '') {
            $next = $next->nextSibling;
        }
        $prevOk = ($prev === null)
            || ($prev->nodeType === XML_ELEMENT_NODE && in_array(strtolower($prev->nodeName), $blockTags, true));
        $nextOk = ($next === null)
            || ($next->nodeType === XML_ELEMENT_NODE && in_array(strtolower($next->nodeName), $blockTags, true));
        if ($prevOk && $nextOk) {
            $toElement($b, 'h3');
        }
    }

    // 11b) Headings keep their own typeface: unwrap inline wrappers
    //      (<b>, <span>, <font>, ...) so heading text is never split
    //      between Prata (heading) and Lato (wrapper) styles.
    $inlineWrap = ['b', 'strong', 'span', 'font', 'i', 'em', 'u', 'small', 'mark'];
    foreach (['h1', 'h2', 'h3', 'h4', 'h5', 'h6'] as $htag) {
        $heads = [];
        foreach ($root->getElementsByTagName($htag) as $hn) {
            $heads[] = $hn;
        }
        foreach ($heads as $hn) {
            // Repeat until stable: unwrapping a <span> can expose a deeper
            // <b>/<i> as a direct child on the next pass.
            while (true) {
                $wrapped = [];
                foreach ($inlineWrap as $wtag) {
                    foreach ($hn->getElementsByTagName($wtag) as $wn) {
                        if ($wn->parentNode === $hn) {
                            $wrapped[] = $wn;
                        }
                    }
                }
                if (!$wrapped) {
                    break;
                }
                foreach ($wrapped as $wn) {
                    while ($wn->firstChild) {
                        $hn->insertBefore($wn->firstChild, $wn);
                    }
                    $hn->removeChild($wn);
                }
            }
        }
    }

    // 12) Responsive table wrappers
    $tables = [];
    foreach ($root->getElementsByTagName('table') as $t) {
        $tables[] = $t;
    }
    foreach ($tables as $t) {
        if (!$t->parentNode) {
            continue;
        }
        $wrap = $dom->createElement('div');
        $wrap->setAttribute('class', 'bd-table-wrap');
        $t->parentNode->insertBefore($wrap, $t);
        $wrap->appendChild($t);
    }

    // 13) Remove empty spacer paragraphs (nbsp-only counts as empty)
    $paras = [];
    foreach ($root->getElementsByTagName('p') as $p) {
        $paras[] = $p;
    }
    foreach ($paras as $p) {
        if (!$p->parentNode || preg_match('/\S/u', str_replace("\xC2\xA0", ' ', $p->textContent))) {
            continue;
        }
        if ($p->getElementsByTagName('img')->length > 0 || $p->getElementsByTagName('iframe')->length > 0) {
            continue;
        }
        $p->parentNode->removeChild($p);
    }

    // 13b) Remove table rows/cells that ended up completely empty
    $rows = [];
    foreach ($root->getElementsByTagName('tr') as $tr) {
        $rows[] = $tr;
    }
    foreach ($rows as $tr) {
        if (!$tr->parentNode) {
            continue;
        }
        $hasContent = false;
        foreach ($tr->childNodes as $cell) {
            if ($cell->nodeType === XML_ELEMENT_NODE
                && preg_match('/\S/u', str_replace("\xC2\xA0", ' ', $cell->textContent))) {
                $hasContent = true;
                break;
            }
        }
        if (!$hasContent) {
            $tr->parentNode->removeChild($tr);
        }
    }

    // 14) Output the cleaned fragment
    $out = '';
    foreach ($root->childNodes as $child) {
        $out .= $dom->saveHTML($child);
    }
    libxml_clear_errors();
    return $out;
}

$out = blog_beautify_content($html);
$romanRex = "/\b(i{1,3}|iv|v|vi{1,3}|ix|x[iv]{0,4})[.)]\s*/iu";
$strip = function ($s, $noise = false) use ($romanRex) {
    $s = preg_replace("/^\xEF\xBB\xBF/", "", $s);
    $s = preg_replace("/<(style|script)\b[^>]*>.*?<\/\1>/is", " ", $s);
    $s = preg_replace("/<[^>]+>/", " ", $s);
    $s = html_entity_decode($s, ENT_QUOTES | ENT_HTML5, "UTF-8");
    if ($noise) $s = preg_replace($romanRex, " ", $s);
    $s = preg_replace("/[\p{P}\p{S}\s]+/u", "", $s);
    if ($noise) $s = preg_replace("/[0-9]/u", "", $s);
    return $s;
};

$dom = new DOMDocument();
libxml_use_internal_errors(true);
$dom->loadHTML('<meta charset="utf-8"><div id="r">' . $out . '</div>', LIBXML_NOWARNING | LIBXML_NOERROR);
$r = $dom->getElementById("r");
$errs = [];
if (mb_strpos($out, "**") !== false) $errs[] = "stray-**";
foreach (["td", "th"] as $t) foreach ($r->getElementsByTagName($t) as $td) foreach ($td->getElementsByTagName("h3") as $h) { $errs[] = "h3-in-td"; break 2; }
foreach (["h1","h2","h3","h4","h5","h6"] as $tag) foreach ($r->getElementsByTagName($tag) as $h) foreach (["b","strong","span","font","i","em"] as $w) if ($h->getElementsByTagName($w)->length) { $errs[] = "wrapper-in-heading"; break 2; }
$stray = [];
foreach ($r->getElementsByTagName("p") as $p) {
    $anc = $p->parentNode; $inLi = false; $inTd = false;
    while ($anc) { $n = strtolower($anc->nodeName); if (in_array($n, ["ol","ul","li"], true)) $inLi = true; if (in_array($n, ["td","th"], true)) $inTd = true; $anc = $anc->parentNode; }
    if ($inLi || $inTd) continue;
    $txt = trim(preg_replace("/\s+/u", " ", $p->textContent));
    if (preg_match("/^\s*(\d{1,2})[.)](?:\s|$)/u", $txt, $m)) $stray[] = (int)$m[1];
}
$ol = $r->getElementsByTagName("ol")->length;
$ul = $r->getElementsByTagName("ul")->length;
$nestedUl = 0;
foreach ($r->getElementsByTagName("ul") as $u) if (strtolower($u->parentNode->nodeName) === "li") $nestedUl++;
$a = $strip($html); $b = $strip($out);
$state = "OK";
if ($a !== $b) { $state = ($strip($html, true) === $strip($out, true)) ? "NOISE-ONLY" : "TEXT-LOSS"; }
echo ($errs ? "ERR " . implode(" ", $errs) : "OK"), " $state stray=", count($stray), " ol=$ol ul=$ul nestedUl=$nestedUl", (count($stray) ? " [" . implode(",", $stray) . "]" : ""), "\n";
